// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDfYFcgeiqeJgiIP318pv40v06gVMt8650',
    appId: '1:542999771798:web:ffe087b37fc212d757a0b7',
    messagingSenderId: '542999771798',
    projectId: 'animalwelfare-aly',
    authDomain: 'animalwelfare-aly.firebaseapp.com',
    storageBucket: 'animalwelfare-aly.firebasestorage.app',
    measurementId: 'G-43P27DK0H2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6rsospd-XeqrtmqI1ia09umjsLAYq2u4',
    appId: '1:542999771798:android:789c7d807bbd032f57a0b7',
    messagingSenderId: '542999771798',
    projectId: 'animalwelfare-aly',
    storageBucket: 'animalwelfare-aly.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCv1Awa5M2Io1mYlktReB16sA7PCH_BzQc',
    appId: '1:542999771798:ios:6a780326d96a495857a0b7',
    messagingSenderId: '542999771798',
    projectId: 'animalwelfare-aly',
    storageBucket: 'animalwelfare-aly.firebasestorage.app',
    iosBundleId: 'com.example.animlawelfare',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDfYFcgeiqeJgiIP318pv40v06gVMt8650',
    appId: '1:542999771798:web:5c2cf347de0c0cf657a0b7',
    messagingSenderId: '542999771798',
    projectId: 'animalwelfare-aly',
    authDomain: 'animalwelfare-aly.firebaseapp.com',
    storageBucket: 'animalwelfare-aly.firebasestorage.app',
    measurementId: 'G-9ET85VEK0X',
  );
}
